# Generated by Django 3.2 on 2023-04-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0002_input_default_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='warehouse',
        ),
    ]
