# Generated by Django 3.2 on 2023-04-20 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0003_remove_order_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор платежа'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='Идентификатор платежа stripe'),
        ),
    ]
