# Generated by Django 3.2 on 2023-04-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0004_auto_20230420_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_paid',
            new_name='paid',
        ),
    ]
