# Generated by Django 3.2 on 2023-04-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0005_rename_is_paid_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Стоимость заказа'),
        ),
    ]
