# Generated by Django 3.2 on 2023-04-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0006_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='cost',
            field=models.PositiveSmallIntegerField(default=2227, verbose_name='Стоимость'),
        ),
    ]
