# Generated by Django 3.2 on 2023-04-20 20:21

from django.db import migrations, models
import self_storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0007_box_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='cost',
            field=models.PositiveSmallIntegerField(default=4890, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(db_index=True, default=self_storage.models.now_plus_30, verbose_name='Дата окончания хранения'),
        ),
    ]
