# Generated by Django 3.2 on 2023-04-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0008_auto_20230420_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='cost',
            field=models.PositiveSmallIntegerField(default=1547, verbose_name='Стоимость'),
        ),
    ]
