# Generated by Django 3.2 on 2023-04-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0009_alter_box_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='cost',
            field=models.PositiveSmallIntegerField(default=3142, verbose_name='Стоимость'),
        ),
    ]
