# Generated by Django 3.2.18 on 2023-04-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0010_alter_box_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='cost',
            field=models.PositiveSmallIntegerField(default=4860, verbose_name='Стоимость'),
        ),
    ]
