# Generated by Django 3.2 on 2023-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0010_alter_box_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='Media', verbose_name='QR-код для доступа'),
        ),
        migrations.AlterField(
            model_name='box',
            name='cost',
            field=models.PositiveSmallIntegerField(default=3098, verbose_name='Стоимость'),
        ),
    ]
