# Generated by Django 3.2 on 2023-04-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0011_alter_box_cost'),
        ('self_storage', '0012_auto_20230423_1825'),
    ]

    operations = [
    ]
