# Generated by Django 3.2 on 2023-04-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0013_merge_0011_alter_box_cost_0012_auto_20230423_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='qr_codes', verbose_name='QR-код для доступа'),
        ),
    ]
